var rule = {
  title: 'JAVXX',
  host: 'https://javxx.com',
  url: 'https://javxx.com/cn/fyclass?page=fypage',
  searchUrl: 'https://javxx.com/cn/search?keyword=**&page=fypage',
  searchable: 2,
  quickSearch: 0,
  filterable: 0,
  filter: '',
  filter_url: '',
  filter_def: {},
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  timeout: 5000,
  class_parse: '#menu&&ul&&li;a&&Text;a&&href;.*/(.*)',
  cate_exclude: '类别|女演员|制作商|系列|SIRO|LUXU|200GANA|PRESTIGE PREMIUM|ORECO|S-CUTE|ARA|390JAC|328HMDN|FC2|HEYZO|1pondo|Caribbeancom|Caribbeancompr|10musume|Pacopacomama|C0930|H0930|H4610|Tokyo Hot|XXX AV|GACHIG',
  play_parse: true,
  lazy: "js:\n  input = { parse: 1, url: input, js: '' };",
  double: true,
  推荐: '列表1;列表2;标题;图片;描述;链接;详情',
  一级: '.vid-items&&.item;span:eq(2)&&Text;img&&src;.meta&&Text;a&&href',
  二级: '*',
  搜索: '*',
}