var rule = {
    title: '双子星',
    host: 'https://1.star2.cn',
    hostJs: '',
    headers: {
        'User-Agent': 'Mozilla/5.0 (Linux; Android 11; Pixel 5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.91 Mobile Safari/537.36',
    },
    编码: 'utf-8',
    timeout: 5000,
    url: 'https://1.star2.cn/fyclass/',
    filter_url: '',
    detailUrl: '',
    searchUrl: 'https://1.star2.cn/search/?keyword=**',
    searchable: 1,
    quickSearch: 1,
    filterable: 1,
    class_name: '短剧&国剧&综艺&电影&韩日&英美&外剧&动漫',
    class_url: 'dj&ju&zy&mv&rh&ym&wj&dm',
    proxy_rule: '',
    sniffer: false,
    isVideo: '',
    play_parse: true,
    parse_url: '',
    lazy: "js:\n        input = 'push://' + input;\n    ",
    limit: 9,
    double: false,
    推荐: '*',
    一级: 'js:\n        let html = fetch(input);\n        let list = pdfa(html, ".erx-list&&li");\n        VODS = list.map(x => {\n            return {\n                vod_name: pdfh(x, "a&&Text"),\n                vod_pic: \'https://fs-im-kefu.7moor-fs1.com/ly/4d2c3f00-7d4c-11e5-af15-41bf63ae4ea0/1746269827120/1.jpeg\',\n                vod_remarks: pdfh(x, "a&&Text"),\n                vod_content: pdfh(x, "a&&Text"),\n                vod_id: pdfh(x, "a&&href")\n            }\n        });\n    ',
    二级: {
        title: 'h1&&Text',
        img: 'https://fs-im-kefu.7moor-fs1.com/ly/4d2c3f00-7d4c-11e5-af15-41bf63ae4ea0/1746269827120/1.jpeg',
        desc: '.card-text:eq(2)&&Text;;;;',
        content: '.card-text:eq(0)&&Text',
        tabs: "js:TABS = ['双星']",
        lists: "js:\n            LISTS = [];\n            let lists1 = pdfa(html, '.dlipp-cont-bd').map(it => {\n                let _tt = pdfh(it, 'a&&Text');\n                let _uu = pdfh(it, 'a&&href');\n                return _tt + '$' + _uu;\n            });\n            LISTS.push(lists1);\n        ",
    },
    搜索: 'js:\n        let html = fetch(input);\n        let list = pdfa(html, ".erx-list&&li");\n        VODS = list.map(x => {\n            return {\n                vod_name: pdfh(x, "a&&Text"),\n                vod_pic: \'https://fs-im-kefu.7moor-fs1.com/ly/4d2c3f00-7d4c-11e5-af15-41bf63ae4ea0/1746269827120/1.jpeg\', \n                vod_remarks: pdfh(x, "a&&Text"),\n                vod_content: pdfh(x, "a&&Text"),\n                vod_id: pdfh(x, "a&&href")\n            }\n        });\n    ',
    cate_exclude: '首页|留言|APP|下载|资讯|新闻|动态',
    tab_exclude: '猜你|喜欢|下载|剧情|榜|评论',
    类型: '影视',
    homeUrl: 'https://1.star2.cn',
    二级访问前: '',
    encoding: 'utf-8',
    search_encoding: '',
    图片来源: '',
    图片替换: '',
    play_json: [],
    pagecount: {},
    tab_remove: [],
    tab_order: [],
    tab_rename: {},
}