var rule = {
  title: 'LIBHD',
  host: 'https://www.libhd.com',
  url: '/vodshow/fyclassfyfilter.html',
  searchUrl: '/vodsearch/**----------fypage---.html',
  searchable: 2,
  quickSearch: 0,
  filterable: 1,
  filter: 'H4sIAAAAAAAAA+2ZWW8aVxTHvwvPruSxszVv2fd9T5WHPPipbd5aqYos2cYQwAvYckwoeGuMcVyDwXZdAwW+zNwZ+BYdc8/5n4sUj1DjVmo0b/z+Z+527py5f2behqzQ+e/ehr4f+SV0PuRW6mp5KjQQevP6xxGTf379w08j3QvfeLKKbHbCm0eyB6HRAVIXcypeIJWAY26s4oQjFCPgmDOecsYWKUaAPhObdiPHfWpAn4U5Va1znxrQLl6Q8QgwXuyDXYvzeBo41i5uqOktihFgvMSO2+AYgTFPd6Eu8zwCxPLvZJ4EmEtxw26u8lw0oF10vpP5xO00oN3yljdzbqehn3w6E9vu4hzHNCAWTjgTv3JMA9ZeT6rIIa9dA8c6S/POhzzFCNDn4rt2vMZ9asD6miV34Q/VqPASwbgiud7+iF3UgNhsVCV3OaYBu9hKeXvAu6hBsppzluaQ1S4gNtlyf+eVECADjTm3nuuZcI80+uroSl1GKldW0zUpI3BfZbRe6GSiPAkNSPVGxjnc4VRrkGSVnWoTyeoCJt+cVdkGT1sDtmjvvcQIkMipisQI0C6dd3Lb3E4D5rnySdoRyLb/KTECmUvZnEu5p91MWdU2uJ0GtJtMeplSMa4WYawk33KTRTee4cWApYRXnamW1wxVzIwrIgd2nQuLoGfbq/t2vWFsO3M/2z40OHSKtO5PQx8WfdjUh0QfMnVLdMvUB0UfNHTrW+jeT0M/J/o5Uz8r+llTPyP6GVM/LfppU5f1WuZ6LVmvZa7XkvVa5notWa9lrteS9Xo/zY1q7xTbm2OyUeC+6jPb8K7nu0CDUS8SI0AN7q5LjAD1km6ombSEhY2KMsIajEqUGIFR3UZMg1GJxko0GPe6KoXlXj+Cnnu9mHZ2Zox7nbmfFF4g4QKUi6RchHKJlEtQLpNyGcoVUq5AuUrKVSjXSLkG5Top16HcIOUGlJuk3IRyi5RbUG6TchvKHVLuQLlLyl0o90i5B+U+KfehPCDlAZSHpDyE8oiUR1Aek/IYyhNSnkB5SspTKM9IeQblOSnPobwg5QWUl6S8hDL4DT9GurX2aiA0dGLG0scG+Jk57UXU+IEKJ3vsCUn9GFdVOlA11IiGPg3hscbVzxD6GVc/y+Nn0OzqmlgeAjF9ESfDjoIA472PiskkMOyQ5Iyg73Pyi+xRNOJdD//WhX5sxz+1Tn42x99WHW9lfG3VYtlzHmppDaaZObAhgQ35v9qQwE4EduIL7cTwSdmJzljcLYzxPazBPA4nV4zj0ANUVanVLse4qjSg3XzRSfCbAwKpi4hzyEczgdTTnl1NoZ66YJwunY88FwLEaluqtMwxDRgvu2u8c9GAdgsrzj7emWlAu8NDJ5a0a/Py7qRHQh72f/MMBudBA/qoTLTHp7m1hv/k6PeOc+/gxrS7YDyYvEeVPJiOALHtgpdajmkIDtPgMA0O0+AwDX29h+mpkzpM/Q5Mvw80brjYXuNDmAB9zm66KX4DToBYatndxgcMDXI+HP/BpJ1aas/yewIC9Lm6prKoNQ3o0+d/vJOrGR9hNGA8n08Qfu8sVNlL0z6Pp8GM5feMmAfI53rT/os/3hCg3eyKimW5nQaO2bVdVWQDQoA+swknw0aCQPJSUa008tIF4/n0L/7/zzbsGl7WaDAemsf+V//sQd/vhAMTEJiAwAQEJuBrMgGjfwPB443K+yEAAA==',
  filter_url: '-{{fl.地区}}--{{fl.类型}}-{{fl.语言}}-{{fl.字母}}---fypage---{{fl.年份}}',
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  timeout: 5000,
  class_parse: '.swiper-wrapper&&li:lt(5);a&&Text;a&&href;(\\d+)',
  play_parse: true,
  lazy: "js:\n  input = { parse: 1, url: input, js: '' };",
  double: true,
  推荐: '*',
  一级: 'body&&.public-list-box;a&&title;img&&data-src;.public-list-prb&&Text;a&&href',
  二级: {
    title: 'h3&&Text;.gen-search-form li:eq(6)--em&&Text',
    img: '.mask-1&&data-src',
    desc: '.gen-search-form li:eq(1)--em&&Text;.gen-search-form li:eq(4)--em&&Text;.gen-search-form li:eq(5)--em&&Text;.gen-search-form li:eq(2)--em&&Text;.gen-search-form li:eq(3)--em&&Text',
    content: '.gen-search-form li:eq(-1)--em&&Text',
    tabs: '.anthology-tab a',
    lists: '.anthology-list-play:eq(#id)&&li',
    tab_text: 'body&&Text',
    list_text: 'body&&Text',
    list_url: 'a&&href',
  },
   搜索: '*;.thumb-txt&&Text;*;*;*;.thumb-blurb&&Text',
}
