{
    "请求头": "User-Agent$MOBILE_UA",
    "主页url": "https://www.aiwodj.com",
    "数组": "lazy lazyloaded&&</a[替换:amp;>>]",
    "图片": "data-src=\"&&\"",
    "标题": "title=\"&&\"",
    "链接": "href=\"&&\"",
    "副标题": "+module-item-caption\">&&</div",
    "简介": "description\" content=\"&&，这里",
    "线路数组": "module-tab-item tab-item&&</div",
    "线路标题": "+span>&&</span",
    "播放数组": "module-blocklist&&</div>",
    "播放列表": "<a&&</a>",
    "播放标题": "span>&&</span>",
    "播放链接": "href=\"&&\"",
    "跳转播放链接": "urlDecode(var player_*\"url\":\"&&\")",
    "搜索url": "https://www.aiwodj.com/vodsearch/{wd}----------{pg}---.html",
    "搜索数组": "lazy lazyload&&</a[替换:amp;>>]",
    "搜索图片": "data-src=\"&&\"",
    "搜索标题": "+title=\"&&\"",
    "搜索链接": "href=\"&&\"",
    "分类url": "https://www.aiwodj.com/vodshow/{cateId}--{by}-{class}-{lang}----{catePg}---{year}.html",
    "分类": "穿越&战神&重生&爱情&萌娃&神医&古代&玄幻&言情",
    "分类值": "fenle&fenlei2&fenlei3&fenlei4&guda&shenyi&gudai&xuanhuan&yanqing"
}