#GET http://robyang.ggff.net/
GET https://smart.pendy.dpdns.org/m3u/Smart.m3u
#GET https://tv.iill.top/m3u/Gather
User-Agent: okhttp/3.2.0
CLIENT-IP: 127.0.0.1
X-FORWARDED-FOR: 127.0.0.1
Content-Type: application/json


###


GET https://www1.RobYang.ggff.net/VodLive/sb8ffa
User-Agent: okhttp/3.2.0
User-Agent: okhttp/3.2.0
CLIENT-IP: 127.0.0.1
X-FORWARDED-FOR: 127.0.0.1
Content-Type: application/json
###


GET https://www1.RobYang.ggff.net/VodLive/jb8ffa
#GET http://robyang.runasp.net/VodLive/jb8ffa
User-Agent: okhttp/3.2.0
User-Agent: okhttp/3.2.0
CLIENT-IP: 127.0.0.1
X-FORWARDED-FOR: 127.0.0.1
Content-Type: application/json


###


GET https://www1.RobYang.ggff.net/VodLive/lb8ffa
User-Agent: okhttp/3.2.0
User-Agent: okhttp/3.2.0
CLIENT-IP: 127.0.0.1
X-FORWARDED-FOR: 127.0.0.1
Content-Type: application/json



###
#GET http://livesmartphp.RobYang.ggff.net/smart2.php?id=starmoviesgold_twn
GET http://livesmartphp.RobYang.ggff.net/smart.php?id=starmoviesgold_twn
User-Agent: okhttp/3.2.0
