name: Sync upstream

on:
  workflow_dispatch:
  schedule:
    - cron: "20 5 * * *"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync from qist/tvbox
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote add upstream https://github.com/qist/tvbox.git
          git fetch upstream master
          git checkout master
          git reset --hard upstream/master
          git push origin master --force
