name: Sync Fork

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v2
        with:
          owner: qist
          repo: tvbox
          head: master
          base: master
          token: ${{ secrets.GITHUB_TOKEN }}
